# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - id: "example-oauth-authc"
    main: ./cmd/authc/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: "example-oauth-fe"
    main: ./cmd/frontend/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - builds: # Builds reference which build instances should be archived in this archive.
      - "example-oauth-authc"
      - "example-oauth-fe"
    format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    allow_different_binary_count: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'